Tt/get schedules
PeterChu2/WATPlanner pull request #22
Opened 2017-06-17 22:34 UTC by timothytong

2017-06-17 22:45 UTC, yongla requested changes
Just some minor stuff

2017-06-17 22:45 UTC, yongla commented on app/src/main/java/com/example/peterchu/watplanner/Database/DatabaseHandler.java
> +        courseComponent.setIsTba(cursor.getInt(15) == 1 ? true : false);
nit: I think we can just do
```
courseComponent.setIsCancelled(cursor.getInt(13) == 1);
courseComponent.setIsClosed(cursor.getInt(14) == 1);
courseComponent.setIsTba(cursor.getInt(15) == 1);

2017-06-17 22:45 UTC, yongla commented on app/src/main/java/com/example/peterchu/watplanner/home/HomePresenter.java
> +                    Log.d("MyActivity", c.toString());
Is this else statement necessary? Looks like it's just for debugging purposes and not needed for master

2017-06-17 22:49 UTC, timothytong commented
Comments addressed

2017-06-18 00:14 UTC, yongla approved these changes
lets get it!

2017-06-18 00:15 UTC, merged